sfbcn_website:
    contactmail: "symfony.barcelona@gmail.com"
    feeds:
      symfonyrssurl: http://feeds.feedburner.com/symfony/blog
      feed2 : http://www.meneame.net/rss2.php      
      feed3 : http://www.elpais.com/rss/feed.html?feedId=1022
      feed4 : http://rss.noticias.lainformacion.com/deporte/